  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["c8:33:32:a1:47:33:fa:9c:62:c9:5e:50:0e:d7:25:80"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for your playbook
            apk add --update ansible 
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main4.yml
  workflows:
    # Name the workflow "welcome"
    my_workflow:
      # Run the welcome/run job in its own container
      jobs:
        - configure_infrastructure            
